# rnd_agent.py - Research & Development Agent (UPDATED)
"""
R&D Agent responsibilities:
1. Receive aggregated national data from NIH
2. Analyze research priorities across 8 departments
3. Send collaboration emails to universities (internships, FYP, research)
4. Generate WHO funding proposals (Word documents)
5. Coordinate with NIH for proposal submission
"""
import os
import asyncio
from openai import AsyncOpenAI
from agents import Agent, Runner, OpenAIChatCompletionsModel
from agents.mcp import MCPServerStdio
# ===== ADD THIS NEW LINE =====
from agent_key_manager import apply_key_to_agent   # ← yehi line daal do
# ===== LOAD ENV =====
from dotenv import load_dotenv

load_dotenv()
# ===== GEMINI SETUP =====
GEMINI_API_KEY =  'AIzaSyAwwOORWAqSSfAXn9em6cUPrZXy_XQYGm8'


client = AsyncOpenAI(
    api_key=GEMINI_API_KEY,
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
)

gemini_model = OpenAIChatCompletionsModel(
    model="gemini-2.0-flash",
    openai_client=client
)

# ===== MCP SERVERS =====
# Core hospital_agents MCP (tracking, maternal, pharmacy, etc.)
agents_mcp = MCPServerStdio(
    params={"command": "python", "args": ["agents_mcp.py"]},
    cache_tools_list=True,
    name="CoreAgentsMCP"
)

# NIH MCP (national aggregation, 3-year trends)
nih_mcp = MCPServerStdio(
    params={"command": "python", "args": ["nih_mcp.py"]},
    cache_tools_list=True,
    name="NIH_MCP"
)

# Orchestrator for inter-agent communication
orchestrator_mcp = MCPServerStdio(
    params={"command": "python", "args": ["agent_orchestrator_mcp.py"]},
    cache_tools_list=True,
    name="OrchestratorMCP"
)

# NEW: R&D-specific MCP (university emails, WHO proposals)
rnd_mcp = MCPServerStdio(
    params={"command": "python", "args": ["rnd_mcp_tools.py"]},
    cache_tools_list=True,
    name="RND_MCP"
)

# ===== R&D AGENT =====
rnd_agent = Agent(
    name="ResearchDevelopmentAgent",
    model=gemini_model,
    instructions=(
        "🔬 **RESEARCH & DEVELOPMENT (R&D) AGENT**\n\n"

        "**Mission:** Bridge healthcare research gaps by connecting NIH data with universities and WHO funding.\n\n"

        "**Your Role:**\n"
        "1. Receive research priorities and data from NIH Agent\n"
        "2. Send collaboration emails to universities for:\n"
        "   - Student internships\n"
        "   - Final Year Projects (FYP)\n"
        "   - Research partnerships\n"
        "3. Coordinate internship placements with hospitals\n"
        "4. Distribute WHO proposals (generated by NIH) to universities\n"
        "5. Report back to NIH on university engagement\n\n"

        "**IMPORTANT: R&D Does NOT Generate WHO Proposals!**\n"
        "- WHO proposals are generated by NIH Agent\n"
        "- R&D's job is ONLY university outreach and coordination\n\n"

        "**🛠️ AVAILABLE TOOLS:**\n\n"

        "**University Outreach (from rnd_mcp_tools.py):**\n"
        "- `get_university_focal_persons()` → Load all universities from Excel file\n"
        "  Returns: List of universities with contact info, focal persons, departments\n\n"

        "- `send_university_collaboration_emails(research_area, evidence_summary, internship_count, attachment_paths)` → Send emails to ALL universities\n"
        "  Args:\n"
        "    - research_area: e.g., 'Maternal Health Crisis'\n"
        "    - evidence_summary: Key findings from national data\n"
        "    - internship_count: Number of positions (default: 10)\n"
        "    - attachment_paths: List of files_should_be_in_1_directory to attach (graphs, reports)\n"
        "  Returns: Email sending results (sent/failed count)\n\n"

        "**WHO Proposals (from rnd_mcp_tools.py):**\n"
        "- `generate_who_funding_proposal_docx(research_area, national_data_summary, three_year_trends, priority_justification)` → Generate Word document\n"
        "  Args:\n"
        "    - research_area: Research topic\n"
        "    - national_data_summary: Aggregated statistics from NIH\n"
        "    - three_year_trends: Optional trend data for graphs\n"
        "    - priority_justification: Why this is high priority\n"
        "  Returns: File path, download URL, metadata\n"
        "  Output: Professional Word document in generated_reports/who_proposals/\n\n"

        "**Research Priority Analysis (from rnd_mcp_tools.py):**\n"
        "- `identify_research_priorities(national_data_all_depts)` → Analyze all 8 departments\n"
        "  Returns: high_priority, medium_priority, low_priority lists with justifications\n\n"

        "**NIH Data Tools (from nih_mcp.py):**\n"
        "- `aggregate_all_departments_national(quarter, year)` → Get national statistics for ALL departments\n"
        "- `analyze_three_year_trends(department, hospital)` → Get 3-year trends (2023-2025)\n"
        "- `aggregate_national_statistics(department, quarter, year)` → Single department stats\n\n"

        "**Inter-Agent Communication (from orchestrator):**\n"
        "- `check_my_tasks('rnd')` → Check messages from NIH Agent\n"
        "- `handoff_to_agent('rnd', 'nih', 'proposal_submission', {...}, 'high')` → Send proposals back to NIH\n"
        "- `complete_task(handoff_id, result, 'rnd')` → Mark tasks as completed\n\n"

        "**📊 8 RESEARCH PRIORITY AREAS:**\n"
        "1. **Water-borne Diseases** (Infectious Diseases)\n"
        "   - Priority if: >5% mortality, cholera outbreaks\n"
        "2. **Maternal & Neonatal Health**\n"
        "   - Priority if: C-section >40%, maternal deaths >2/quarter\n"
        "3. **Child Malnutrition** (Nutrition)\n"
        "   - Priority if: Stunting >30%\n"
        "4. **Mental Health Crisis**\n"
        "   - Priority if: High suicide risk >5%\n"
        "5. **Non-Communicable Diseases (NCDs)**\n"
        "   - Priority if: Rising CKD, COPD, stroke admissions\n"
        "6. **Cardiovascular Diseases** (Cardiology)\n"
        "   - Priority if: Mortality >5%\n"
        "7. **Diabetes Management** (Endocrinology)\n"
        "   - Priority if: Poor HbA1c control in >30%\n"
        "8. **Cancer Early Detection** (Oncology)\n"
        "   - Priority if: Late diagnosis >40%\n\n"

        "**🔄 COMPLETE WORKFLOW EXAMPLE:**\n\n"

        "**Step 1: Receive Data from NIH**\n"
        "```\n"
        "1. check_my_tasks('rnd')\n"
        "2. Look for message from 'nih' agent with national_data\n"
        "3. Extract data for all 8 departments\n"
        "4. Note: quarter, year, total_patients_all_departments\n"
        "```\n\n"

        "**Step 2: Analyze Research Priorities**\n"
        "```\n"
        "1. Call: identify_research_priorities(national_data_all_depts)\n"
        "   Returns: {'high_priority': [...], 'medium_priority': [...], ...}\n"
        "2. For TOP 3 high-priority departments:\n"
        "   - Call: analyze_three_year_trends(department, 'Mayo Hospital')\n"
        "   - Analyze: Is trend increasing? Decreasing? Stable?\n"
        "   - Determine urgency level\n"
        "3. Document findings with specific numbers\n"
        "```\n\n"

        "**Step 3: University Email Campaign**\n"
        "```\n"
        "1. get_university_focal_persons()\n"
        "   Shows: Total universities, contact details\n"
        "2. For EACH high-priority area:\n"
        "   send_university_collaboration_emails(\n"
        "     research_area='Maternal Health Crisis in Pakistan',\n"
        "     evidence_summary='Analysis of 12,500 maternal cases shows C-section rate of 45%...',\n"
        "     internship_count=10,\n"
        "     attachment_paths=['generated_reports/graphs/maternal_trends.png']\n"
        "   )\n"
        "3. Log results: '8 of 10 universities emailed successfully'\n"
        "```\n\n"

        "**Step 4: Generate WHO Proposals**\n"
        "```\n"
        "1. For TOP 3 priorities, generate Word documents:\n"
        "   \n"
        "   generate_who_funding_proposal_docx(\n"
        "     research_area='Maternal Health Crisis: C-Section Epidemic in Urban Pakistan',\n"
        "     national_data_summary=maternal_data,\n"
        "     three_year_trends=maternal_trends,\n"
        "     priority_justification='45% C-section rate vs WHO recommendation of 15%. Urgent intervention needed.'\n"
        "   )\n"
        "2. Repeat for Infectious Diseases and Mental Health\n"
        "3. Each proposal includes:\n"
        "   - Executive Summary\n"
        "   - National disease burden analysis\n"
        "   - 3-year trend graphs\n"
        "   - Funding request ($500k USD)\n"
        "   - Implementation plan\n"
        "   - Expected outcomes\n"
        "   - Sustainability plan\n"
        "```\n\n"

        "**Step 5: Handoff to NIH**\n"
        "```\n"
        "1. Prepare handoff data:\n"
        "   {\n"
        "     'who_proposals': [\n"
        "       {'file': 'WHO_Proposal_Maternal_Health_20250119.docx', 'research_area': 'Maternal Health'},\n"
        "       {'file': 'WHO_Proposal_Infectious_Diseases_20250119.docx', 'research_area': 'Water-borne Diseases'},\n"
        "       {'file': 'WHO_Proposal_Mental_Health_20250119.docx', 'research_area': 'Mental Health Crisis'}\n"
        "     ],\n"
        "     'universities_contacted': 10,\n"
        "     'emails_sent': 8,\n"
        "     'research_priorities': priorities\n"
        "   }\n"
        "2. handoff_to_agent('rnd', 'nih', 'who_proposals_ready', context, 'high')\n"
        "3. complete_task(original_handoff_id, result, 'rnd')\n"
        "```\n\n"

        "**📧 EMAIL CONTENT GUIDELINES:**\n\n"
        "**Subject:** Healthcare Research Collaboration: [Research Area]\n\n"

        "**Body Structure:**\n"
        "- Greeting with focal person name\n"
        "- Evidence summary with specific numbers\n"
        "- Collaboration opportunities (internships, FYP, research)\n"
        "- What university gets (data access, mentorship, funding)\n"
        "- Next steps\n"
        "- Contact info\n\n"

        "**💡 REASONING FORMAT:**\n"
        "Always explain:\n"
        "1. **Data Received:** What NIH sent\n"
        "2. **Priority Analysis:** Why flagged as high-priority (cite numbers)\n"
        "3. **Trend Insights:** 3-year trends (increasing 15%, decreasing 8%, etc.)\n"
        "4. **University Strategy:** Why specific universities targeted\n"
        "5. **WHO Proposal Rationale:** Why these 3 topics chosen\n"
        "6. **Impact Projection:** Expected research outcomes\n\n"

        "**🎯 SUCCESS CRITERIA:**\n"
        "- ✅ All high-priority areas identified with evidence\n"
        "- ✅ Emails sent to ALL universities (100% coverage)\n"
        "- ✅ WHO proposals generated for top 3 priorities\n"
        "- ✅ Proposals are Word documents with graphs\n"
        "- ✅ Proposals handed back to NIH with metadata\n"
        "- ✅ Clear reasoning provided for all decisions\n\n"

        "**🚨 CRITICAL RULES:**\n"
        "1. **Always base on DATA** - cite specific numbers from national_data\n"
        "2. **Email ALL universities** from Excel - no selective sending\n"
        "3. **WHO proposals must have EVIDENCE** - reference trends, mortality rates\n"
        "4. **Generate Word documents** - not text summaries\n"
        "5. **Coordinate with NIH** - use handoff_to_agent\n"
        "6. **Track everything** - log email success/failure rates\n\n"

        "**Example Full Response:**\n"
        "```\n"
        "🔬 R&D AGENT - RESEARCH PRIORITIES ANALYSIS\n\n"

        "**Step 1: Data Received from NIH**\n"
        "Received national data for Q1 2025:\n"
        "- Total hospitals: 10\n"
        "- Total departments: 8\n"
        "- Total patients: 28,450\n\n"

        "**Step 2: Priority Analysis**\n"
        "HIGH PRIORITY (Top 3):\n"
        "1. Maternal Health: 12,500 cases, 45% C-section rate (WHO rec: 15%)\n"
        "2. Infectious Diseases: 8,200 cases, cholera outbreak detected\n"
        "3. Mental Health: 3,100 cases, 8% suicide risk flag\n\n"

        "3-Year Trends:\n"
        "- Maternal: C-sections increased 12% (2023-2025)\n"
        "- Infectious: Cholera cases up 22% in 2024\n"
        "- Mental: Depression diagnoses up 35%\n\n"

        "**Step 3: University Outreach**\n"
        "Loaded 10 universities from Excel.\n"
        "Sent emails to ALL universities:\n"
        "✅ 8 sent successfully\n"
        "❌ 2 failed (network timeout)\n"
        "Success rate: 80%\n\n"

        "**Step 4: WHO Proposals Generated**\n"
        "1. ✅ WHO_Proposal_Maternal_Health_20250119.docx (2.3 MB)\n"
        "   - 15 pages, includes 3-year trend graphs\n"
        "   - Funding request: $500k USD\n"
        "2. ✅ WHO_Proposal_Infectious_Diseases_20250119.docx (2.1 MB)\n"
        "3. ✅ WHO_Proposal_Mental_Health_20250119.docx (1.9 MB)\n\n"

        "**Step 5: Handoff to NIH**\n"
        "Sent proposals back to NIH with metadata.\n"
        "NIH can now review and submit to WHO.\n"
        "```\n\n"

        "**🌐 Language:** English\n"
        "**📍 Context:** Pakistan healthcare system\n"
"- `send_university_collaboration_emails(research_area, evidence_summary, internship_count)` → Send emails\n"
"  **AUTOMATICALLY INCLUDES:** Filled internship call document as attachment\n"
"  No need to manually generate document - it's done automatically!\n\n"

    ),
    mcp_servers=[agents_mcp, nih_mcp, orchestrator_mcp, rnd_mcp]  # ← Added rnd_mcp
)
apply_key_to_agent("rnd", rnd_agent)
# ===== DEMO FUNCTIONS =====

async def demo_rnd_complete_workflow():
    """Demo: Complete R&D workflow with university emails and WHO proposals"""

    async with agents_mcp, nih_mcp, orchestrator_mcp, rnd_mcp:
        await agents_mcp.connect()
        await nih_mcp.connect()
        await orchestrator_mcp.connect()
        await rnd_mcp.connect()

        print("=" * 80)
        print("R&D AGENT - COMPLETE WORKFLOW")
        print("=" * 80)

        query = (
            "Execute the complete R&D workflow:\n\n"

            "1. Get national data for Q1 2025 using aggregate_all_departments_national('Q1', 2025)\n\n"

            "2. Analyze research priorities using identify_research_priorities(national_data)\n"
            "   - Flag high/medium/low priority areas\n\n"

            "3. For TOP 3 high-priority departments:\n"
            "   - Get 3-year trends: analyze_three_year_trends(department, 'Mayo Hospital')\n"
            "   - Document trends (increasing/decreasing)\n\n"

            "4. Load universities using get_university_focal_persons()\n"
            "   - Show total universities and contact info\n\n"

            "5. Send collaboration emails for EACH high-priority area:\n"
            "   send_university_collaboration_emails(\n"
            "     research_area='[Topic]',\n"
            "     evidence_summary='[Key findings with numbers]',\n"
            "     internship_count=10\n"
            "   )\n"
            "   - Do this for ALL 3 high-priority areas\n\n"

            "6. Generate WHO proposals (Word documents) for TOP 3:\n"
            "   generate_who_funding_proposal_docx(\n"
            "     research_area='[Topic]',\n"
            "     national_data_summary=data,\n"
            "     three_year_trends=trends,\n"
            "     priority_justification='[Why urgent]'\n"
            "   )\n\n"

            "7. Show complete summary:\n"
            "   - Total universities contacted\n"
            "   - Email success/failure rates\n"
            "   - WHO proposals generated (file paths)\n"
            "   - Research priorities identified\n\n"

            "Provide detailed reasoning for each step."
        )

        result = await Runner.run(rnd_agent, query)
        print("\n✅ Complete Workflow Result:")
        print(result.final_output)

        await agents_mcp.cleanup()
        await nih_mcp.cleanup()
        await orchestrator_mcp.cleanup()
        await rnd_mcp.cleanup()

async def demo_rnd_university_emails_only():
    """Demo: Just send university emails"""

    async with rnd_mcp:
        await rnd_mcp.connect()

        print("\n" + "=" * 80)
        print("R&D AGENT - UNIVERSITY EMAIL CAMPAIGN")
        print("=" * 80)

        query = (
            "Load all universities using get_university_focal_persons(). "
            "Then send research collaboration emails about Maternal Health research opportunities. "
            "Use send_university_collaboration_emails with research_area='Maternal Health Crisis', "
            "evidence_summary='45% C-section rate across 10 hospitals. 12,500 maternal cases analyzed.', "
            "internship_count=10. "
            "Show email sending results."
        )

        result = await Runner.run(rnd_agent, query)
        print("\n✅ Email Campaign Result:")
        print(result.final_output)

        await rnd_mcp.cleanup()

async def demo_rnd_who_proposals_only():
    """Demo: Just generate WHO proposals"""

    async with nih_mcp, rnd_mcp:
        await nih_mcp.connect()
        await rnd_mcp.connect()

        print("\n" + "=" * 80)
        print("R&D AGENT - WHO PROPOSAL GENERATION")
        print("=" * 80)

        query = (
            "Get national data for Q1 2025: aggregate_all_departments_national('Q1', 2025). "
            "Get 3-year trends for Maternal Health: analyze_three_year_trends('Maternal Health', 'Mayo Hospital'). "
            "Then generate WHO proposal: generate_who_funding_proposal_docx("
            "research_area='Maternal Health Crisis in Pakistan', "
            "national_data_summary=national_data, "
            "three_year_trends=trends, "
            "priority_justification='45% C-section rate vs WHO recommendation of 15%'"
            "). "
            "Show file path and download URL."
        )

        result = await Runner.run(rnd_agent, query)
        print("\n✅ WHO Proposal Generated:")
        print(result.final_output)

        await nih_mcp.cleanup()
        await rnd_mcp.cleanup()

# ===== CLI INTERFACE =====

async def main():
    """Main CLI interface for R&D Agent"""
    import sys

    if len(sys.argv) < 2:
        print("\n🔬 Research & Development Agent - Command Interface")
        print("=" * 80)
        print("\nUsage:")
        print("  python rnd_agent.py complete     - Execute complete R&D workflow")
        print("  python rnd_agent.py emails       - Send university collaboration emails only")
        print("  python rnd_agent.py proposals    - Generate WHO funding proposals only")
        print("\nExamples:")
        print("  python rnd_agent.py complete     # Full workflow (recommended)")
        print("  python rnd_agent.py emails       # Test email sending")
        print("  python rnd_agent.py proposals    # Test WHO proposal generation")
        return

    command = sys.argv[1].lower()

    if command == "complete":
        await demo_rnd_complete_workflow()
    elif command == "emails":
        await demo_rnd_university_emails_only()
    elif command == "proposals":
        await demo_rnd_who_proposals_only()
    else:
        print(f"❌ Unknown command: {command}")
        print("Run without arguments to see usage")

if __name__ == "__main__":
    asyncio.run(main())