# report_generator.py - Generate PDF Reports with Signatures
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime
import pandas as pd


def generate_department_report_pdf(
        department: str,
        hospital: str,
        quarter: str,
        year: int,
        statistics: dict,
        graphs: dict,
        focal_person_info: dict,
        output_filename: str
):
    """
    📄 Generate professional PDF report with signature

    Args:
        department: Department name
        hospital: Hospital name
        quarter: Q1, Q2, Q3, Q4
        year: Year
        statistics: Dict with stats
        graphs: Dict with base64 graph images
        focal_person_info: {name, email, phone}
        output_filename: PDF output path
    """

    doc = SimpleDocTemplate(output_filename, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=12,
        alignment=1  # Center
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#dc2626'),
        spaceAfter=10
    )

    # Title
    title = Paragraph(
        f"<b>{hospital}</b><br/>"
        f"{department} Quarterly Report<br/>"
        f"Period: {quarter} {year}",
        title_style
    )
    story.append(title)
    story.append(Spacer(1, 0.3 * inch))

    # Executive Summary
    story.append(Paragraph("1. Executive Summary", heading_style))

    summary_data = [
        ['Indicator', 'Value'],
        ['Total Cases', str(statistics.get('total_registered', 0))],
        ['High Risk Cases', str(statistics.get('high_risk_count', 0))],
        ['Completion Rate', f"{statistics.get('anc_visits', {}).get('compliance_rate', 0)}%"],
        ['Average Hemoglobin', f"{statistics.get('avg_hemoglobin', 0)} g/dL"]
    ]

    summary_table = Table(summary_data, colWidths=[3 * inch, 2 * inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3b82f6')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))

    story.append(summary_table)
    story.append(Spacer(1, 0.5 * inch))

    # Graphs section
    story.append(Paragraph("2. Data Visualizations", heading_style))

    # Note: You'd decode base64 graphs and insert as images here
    # For now, placeholder
    story.append(Paragraph("Graphs: Age Distribution, Risk Distribution, ANC Completion", styles['Normal']))
    story.append(Spacer(1, 0.5 * inch))

    # Focal Person Signature
    story.append(Spacer(1, inch))
    story.append(Paragraph("Report Generated by:", heading_style))

    signature_data = [
        ['Focal Person Name:', focal_person_info['name']],
        ['Department:', department],
        ['Email:', focal_person_info['email']],
        ['Phone:', focal_person_info['phone']],
        ['Date:', datetime.now().strftime('%B %d, %Y')],
        ['Signature:', '____________________']
    ]

    signature_table = Table(signature_data, colWidths=[2 * inch, 4 * inch])
    signature_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8)
    ]))

    story.append(signature_table)

    # Footer
    story.append(Spacer(1, 0.5 * inch))
    footer = Paragraph(
        "<i>Generated with Hospital Health Agent - Powered by AI</i>",
        ParagraphStyle('Footer', fontSize=8, textColor=colors.grey, alignment=1)
    )
    story.append(footer)

    # Build PDF
    doc.build(story)
    print(f"✅ PDF report generated: {output_filename}")

    return output_filename


def get_focal_person_info(hospital: str, department: str) -> dict:
    """Get focal person details from Excel"""

    try:
        df = pd.read_excel("focal_persons_excels/hospital_focal_persons.xlsx")

        row = df[
            (df['Hospital'] == hospital) &
            (df['Department'] == department)
            ].iloc[0]

        return {
            "name": row['Focal Person Name'],
            "email": row['Email'],
            "phone": row['Contact']
        }
    except Exception as e:
        print(f"⚠️ Error loading focal person: {e}")
        return {
            "name": "Unknown",
            "email": "unknown@example.com",
            "phone": "N/A"
        }


# Example usage
if __name__ == "__main__":
    stats = {
        "total_registered": 2500,
        "high_risk_count": 100,
        "anc_visits": {"compliance_rate": 88},
        "avg_hemoglobin": 11.5
    }

    focal = get_focal_person_info("Mayo Hospital", "Cardiology")

    generate_department_report_pdf(
        department="Cardiology",
        hospital="Mayo Hospital",
        quarter="Q1",
        year=2025,
        statistics=stats,
        graphs={},
        focal_person_info=focal,
        output_filename="mayo_cardiology_q1_2025.pdf"
    )